[project]
name = "caultron"
version = "2025.34.1"
description = "Secure Key derivation via Cellular Automata, Chacha20 and SHA."
readme = "README.md"
requires-python = ">=3.10"

authors = [
  { name = "Anselm Kiefner", email = "caultron-github@anselm.kiefner.de" }
]
license = "Apache-2.0"
repository = "https://github.com/amogorkon/caultron"
keywords = ["cryptography", "cellular automaton", "key derivation", "entropy"]

packages = [
  { include = "caultron", from = "src" }
]

[project.dependencies]
python = ">=3.10"
numpy = "*"
numba = "*"
matplotlib = "*"

[project.optional-dependencies]
dev = [
  "pytest>=8.2.2",
]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"